# Generated by Django 5.2.8 on 2025-12-08 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Katenya & Faith Wedding', max_length=200)),
                ('event_type', models.CharField(choices=[('WEDDING', 'Wedding'), ('PRE_WEDDING', 'Pre-Wedding / Ruracio'), ('FUNERAL', 'Funeral'), ('GRADUATION', 'Graduation'), ('BIRTHDAY', 'Birthday Party'), ('ANNIVERSARY', 'Anniversary'), ('CONFERENCE', 'Corporate Conference'), ('CONCERT', 'Music Concert'), ('OTHER', 'Other')], max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('client_name', models.CharField(max_length=100)),
                ('client_contact', models.CharField(max_length=15)),
                ('staff_in_charge', models.CharField(help_text='Who is handling the gear?', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('items', models.ManyToManyField(blank=True, related_name='events', to='inventory.inventoryitem')),
                ('planner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
