# Generated by Django 5.2.8 on 2025-12-10 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Last user to edit this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_edits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Mark true when gear is returned'),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(help_text='The owner/creator of the event', on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
    ]
