# Generated by Django 5.2.8 on 2026-02-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft (Planning)'), ('REQUESTED', 'Requested (Awaiting Approval)'), ('APPROVED', 'Approved (Ready)'), ('ACTIVE', 'Active (In Progress)'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='eventitem',
            name='locked_daily_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='eventitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved by Vendor'), ('REJECTED', 'Rejected / Unavailable'), ('DISPATCHED', 'Scanned Out (Active)'), ('RETURNED', 'Scanned In (Completed)')], default='PENDING', max_length=20),
        ),
    ]
