# Generated by Django 5.2.8 on 2026-02-07 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventitem',
            name='item_name_snapshot',
            field=models.CharField(blank=True, help_text='Preserves item name if original item is deleted', max_length=200),
        ),
        migrations.AlterField(
            model_name='eventitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryitem'),
        ),
    ]
