# Generated by Django 5.2.8 on 2025-12-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_updated_at_event_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='labor_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Crew Payment', max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='miscellaneous_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Food/Permits', max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='transport_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Fuel/Uber/Van', max_digits=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='client_contact',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='client_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='staff_in_charge',
            field=models.CharField(blank=True, help_text='Lead Creative on site', max_length=100),
        ),
        migrations.AlterField(
            model_name='eventitem',
            name='condition_return',
            field=models.CharField(choices=[('GOOD', 'Good'), ('DAMAGED', 'Damaged'), ('LOST', 'Lost')], default='GOOD', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventitem',
            name='scanned_in_at',
            field=models.DateTimeField(blank=True, help_text='Time returned via app', null=True),
        ),
        migrations.AlterField(
            model_name='eventitem',
            name='scanned_out_at',
            field=models.DateTimeField(blank=True, help_text='Time scanned out via app', null=True),
        ),
    ]
