# Generated by Django 5.2.8 on 2026-03-04 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_status_eventitem_locked_daily_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='daraja_receipt_number',
            field=models.CharField(blank=True, help_text='M-Pesa transaction ID', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='escrow_status',
            field=models.CharField(choices=[('NONE', 'Not in Escrow'), ('PENDING', 'Awaiting M-Pesa Auth'), ('LOCKED', 'Locked in Vault'), ('RELEASED', 'Paid to Vendor'), ('DISPUTED', 'In Dispute')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='client',
            field=models.ForeignKey(blank=True, help_text='The registered Client (from Sticky Cart)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_gigs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='terms',
            field=models.TextField(blank=True, default='1. 70% Deposit required.\n2. Balance due on delivery. Protected by Gigs360 Escrow.'),
        ),
        migrations.AlterField(
            model_name='document',
            name='user',
            field=models.ForeignKey(help_text='Vendor issuing the doc', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(help_text='The Vendor/Creator managing the event', on_delete=django.db.models.deletion.CASCADE, related_name='vendor_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
