# Generated by Django 5.2.8 on 2026-01-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_is_completed_alter_event_labor_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='client_email',
            field=models.EmailField(blank=True, help_text='Used for auto-filling invoices', max_length=254, null=True),
        ),
    ]
