# Generated by Django 5.2.8 on 2026-03-04 12:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0003_document_daraja_receipt_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., Sam & Ruth Wedding Highlights', max_length=200)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='gallery_covers/')),
                ('access_pin', models.CharField(db_index=True, editable=False, max_length=6)),
                ('is_published', models.BooleanField(default=False, help_text='If false, clients cannot see the gallery link at all.')),
                ('total_size_bytes', models.BigIntegerField(default=0, help_text='Tracks total S3 usage for this gallery')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(help_text='The gig this media belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='events.event')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Galleries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('high_res_file', models.ImageField(upload_to='galleries/high_res/')),
                ('watermarked_file', models.ImageField(blank=True, null=True, upload_to='galleries/watermarked/')),
                ('file_size_bytes', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='galleries.gallery')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
