# Generated by Django 5.2.8 on 2026-03-08 20:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('CREATED', 'Gallery Created'), ('PIN_CHANGED', 'Security PIN Changed'), ('VIEWED', 'Client Unlocked Gallery'), ('DOWNLOADED', 'High-Res Photo Downloaded'), ('SHARED', 'Gallery Link Shared')], max_length=20)),
                ('actor', models.CharField(max_length=100)),
                ('details', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='galleries.gallery')),
            ],
            options={
                'verbose_name_plural': 'Gallery Activities',
                'ordering': ['-timestamp'],
            },
        ),
    ]
