# Generated by Django 5.2.8 on 2026-03-16 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_document_daraja_receipt_number_and_more'),
        ('galleries', '0002_galleryactivity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='vendor',
            new_name='photographer',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='file_size_bytes',
            new_name='file_size',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='high_res_file',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='name',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='total_size_bytes',
        ),
        migrations.AddField(
            model_name='gallery',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(default='Untitled', help_text='e.g., The Smith Wedding', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='access_pin',
            field=models.CharField(blank=True, help_text='Optional 6-digit PIN', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Optional: Link to an event for Invoice/Escrow locking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='galleries', to='events.event'),
        ),
    ]
