# Generated by Django 5.2.8 on 2026-02-28 20:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidaymessage',
            name='is_birthday_automation',
            field=models.BooleanField(default=False, help_text="If checked, this message acts as a template and sends automatically on a user's birthday."),
        ),
        migrations.AddField(
            model_name='holidaymessage',
            name='manual_recipients',
            field=models.ManyToManyField(blank=True, help_text='Search and add specific users by ID/Email. Overrides role targeting.', related_name='manual_broadcasts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='holidaymessage',
            name='target_categories',
            field=models.ManyToManyField(blank=True, help_text='Send only to users who own gear in these categories. (Leave blank for no category filter)', to='inventory.category'),
        ),
        migrations.AddField(
            model_name='holidaymessage',
            name='target_role',
            field=models.CharField(choices=[('ALL', 'All Users (Global Broadcast)'), ('VENDOR', 'Vendors / Agencies Only'), ('FREELANCER', 'Freelance Professionals Only'), ('CLIENT', 'Standard Clients Only')], default='ALL', max_length=20),
        ),
        migrations.AlterField(
            model_name='holidaymessage',
            name='message_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='holidaymessage',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
