# Generated by Django 5.2.8 on 2025-12-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_activity',
            new_name='subscription_expiry',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_expires_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='number_of_employees',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscription_plan',
            field=models.CharField(choices=[('Free', 'Free Starter'), ('Pro', 'Pro Business'), ('Enterprise', 'Enterprise')], default='Free', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='theme_preference',
            field=models.CharField(blank=True, choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10),
        ),
    ]
