# Generated by Django 5.2.8 on 2025-12-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, help_text='e.g. GIG-EMP-001', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='staff_role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Super Admin'), ('UX_EXPERT', 'UX/UI Designer'), ('DEV', 'Software Engineer'), ('MARKETING', 'Marketing Lead'), ('FINANCE', 'Finance Manager'), ('SUPPORT', 'Customer Support')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='business_type',
            field=models.CharField(blank=True, choices=[('PHOTO', 'Photography & Video'), ('DECOR', 'Decor & Flowers'), ('ENT', 'MC & DJ'), ('PLANNING', 'Event Planning'), ('SECURITY', 'Security & Bouncers'), ('CATERING', 'Catering'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10),
        ),
    ]
