# Generated by Django 5.2.8 on 2026-01-31 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Jamhuri Day', max_length=100)),
                ('send_date', models.DateField(help_text='When to send this message')),
                ('message_content', models.TextField(help_text='SMS content (max 160 chars)', max_length=160)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_plan',
        ),
        migrations.AddField(
            model_name='user',
            name='company_logo',
            field=models.ImageField(blank=True, help_text='Used on PDF Invoices', null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='For automated birthday wishes', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, help_text='e.g. GIG-EMP-001', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='invoice_color_theme',
            field=models.CharField(default='#003366', help_text='Hex code for invoice header background (e.g. #003366)', max_length=7),
        ),
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.CharField(choices=[('FREE', 'Free Starter'), ('PRO', 'Pro Business'), ('ENTERPRISE', 'Enterprise')], default='FREE', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='staff_role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Super Admin'), ('UX_EXPERT', 'UX/UI Designer'), ('DEV', 'Software Engineer'), ('MARKETING', 'Marketing Lead'), ('FINANCE', 'Finance Manager'), ('SUPPORT', 'Customer Support')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='business_type',
            field=models.CharField(blank=True, choices=[('PHOTO', 'Photography & Video'), ('DECOR', 'Decor & Flowers'), ('ENT', 'MC & DJ'), ('PLANNING', 'Event Planning'), ('SECURITY', 'Security & Bouncers'), ('CATERING', 'Catering'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, help_text='URL to redirect to when clicked', max_length=255, null=True)),
                ('notification_type', models.CharField(choices=[('success', 'Success'), ('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger')], default='info', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
