# Generated by Django 5.2.8 on 2026-02-07 06:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_holidaymessage_remove_user_subscription_plan_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_logo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='invoice_color_theme',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_client',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_planner',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_vendor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mpesa_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='number_of_employees',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='staff_role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_expiry',
        ),
        migrations.RemoveField(
            model_name='user',
            name='theme_preference',
        ),
        migrations.AddField(
            model_name='holidaymessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='holidaymessage',
            name='message_content',
            field=models.TextField(help_text='SMS content', max_length=160),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('danger', 'Critical Alert')], default='info', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('action', models.CharField(choices=[('LOGIN', 'Login Success'), ('LOGIN_FAIL', 'Login Failed'), ('LOGOUT', 'Logout'), ('SUDO_MODE', 'Critical Action'), ('BAN_IP', 'IP Banned'), ('PASSWORD_CHANGE', 'Password Changed'), ('STAFF_ACCESS', 'Staff Accessed User Account')], max_length=50)),
                ('details', models.TextField(help_text='User Agent, Device Info')),
                ('is_suspicious', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_picture', models.ImageField(blank=True, default='avatars/default.png', upload_to='avatars/')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('kra_pin', models.CharField(blank=True, help_text='Required for Invoicing', max_length=20, null=True, unique=True)),
                ('id_number', models.CharField(blank=True, help_text='National ID / Passport', max_length=20, null=True, unique=True)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('business_name', models.CharField(blank=True, max_length=100)),
                ('company_logo', models.ImageField(blank=True, help_text='Used on PDF Invoices', null=True, upload_to='logos/')),
                ('invoice_color_theme', models.CharField(default='#003366', help_text='Hex code for invoices', max_length=7)),
                ('business_category', models.CharField(choices=[('Photography & Video', 'Photography & Video'), ('Sound & DJ', 'Sound & DJ'), ('Decor & Flowers', 'Decor & Flowers'), ('Event Planning', 'Event Planning'), ('Transport & Logistics', 'Transport & Logistics'), ('Security & Bouncers', 'Security & Bouncers'), ('Catering', 'Catering'), ('Other', 'Other')], default='Other', max_length=50)),
                ('is_freelancer', models.BooleanField(default=False)),
                ('is_vendor', models.BooleanField(default=False)),
                ('is_agency', models.BooleanField(default=False)),
                ('plan', models.CharField(choices=[('FREE', 'Free Starter'), ('PRO', 'Pro Business'), ('ENTERPRISE', 'Enterprise')], default='FREE', max_length=20)),
                ('subscription_end_date', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('is_2fa_enabled', models.BooleanField(default=False)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('terms_version', models.CharField(blank=True, max_length=50)),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('mpesa_number', models.CharField(blank=True, max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
