# Generated by Django 5.2.8 on 2026-03-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_holidaymessage_is_birthday_automation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidaymessage',
            name='target_role',
            field=models.CharField(choices=[('ALL', 'All Users (Global Broadcast)'), ('VENDOR', 'Vendors / Agencies Only'), ('FREELANCER', 'Freelance Professionals Only'), ('CLIENT', 'Standard Clients Only'), ('INDIVIDUAL', 'Specific Individuals')], default='ALL', max_length=20),
        ),
    ]
