# Generated by Django 5.2.8 on 2026-01-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscription_plan',
        ),
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.CharField(choices=[('FREE', 'Free Starter'), ('PRO', 'Pro Business'), ('ENTERPRISE', 'Enterprise')], default='FREE', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('success', 'Success'), ('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger')], default='info', max_length=20),
        ),
    ]
