# Generated by Django 5.2.8 on 2026-01-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_subscription_plan_user_plan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Jamhuri Day', max_length=100)),
                ('send_date', models.DateField(help_text='When to send this message')),
                ('message_content', models.TextField(help_text='SMS content (max 160 chars)', max_length=160)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='company_logo',
            field=models.ImageField(blank=True, help_text='Used on PDF Invoices', null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='For automated birthday wishes', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='invoice_color_theme',
            field=models.CharField(default='#003366', help_text='Hex code for invoice header background (e.g. #003366)', max_length=7),
        ),
    ]
