# Generated by Django 5.2.8 on 2026-04-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_servicefeature_testimonial_upcomingactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ai_trust_score',
            field=models.FloatField(default=50.0, help_text='0-100 score updated by future ML microservices.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kyc_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending Review'), ('APPROVED', 'Verified & Active'), ('FLAGGED', 'Flagged for Fraud/Duplicate'), ('REJECTED', 'Rejected')], default='UNVERIFIED', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason sent to user if rejected.', null=True),
        ),
    ]
