# Generated by Django 5.2.8 on 2026-03-04 10:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0003_document_daraja_receipt_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('C2B_ESCROW', 'Client Deposit to Escrow'), ('B2C_PAYOUT', 'Escrow Release to Vendor'), ('B2C_REFUND', 'Escrow Refund to Client')], default='C2B_ESCROW', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('phone_number', models.CharField(help_text='Format: 2547XXXXXXXX', max_length=15)),
                ('merchant_request_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending User Action (Awaiting PIN)'), ('SUCCESS', 'Completed Successfully (Funds Locked)'), ('FAILED', 'Transaction Failed/Cancelled')], default='PENDING', max_length=20)),
                ('result_code', models.CharField(blank=True, help_text='Safaricom ResultCode (0 is success)', max_length=10, null=True)),
                ('result_desc', models.TextField(blank=True, help_text='Safaricom ResultDesc', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_payments', to='events.document')),
                ('user', models.ForeignKey(blank=True, help_text='User initiating/receiving the transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'M-Pesa Transaction',
                'verbose_name_plural': 'M-Pesa Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
