# Generated by Django 5.2.8 on 2026-03-08 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated from name', unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(default='bi-hash', help_text='Bootstrap icon class (e.g., bi-chat-dots)', max_length=50)),
                ('space_type', models.CharField(choices=[('text', 'Standard Discussion'), ('gig_board', 'Gig & Job Board'), ('announcement', 'HQ Announcements')], default='text', max_length=20)),
                ('is_premium_only', models.BooleanField(default=False, help_text='Restrict access to Pro/Verified users only')),
                ('order', models.IntegerField(default=0, help_text='Lower numbers appear first in the sidebar')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField()),
                ('is_gig_offer', models.BooleanField(default=False, help_text='Flags this post as a hiring opportunity')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, help_text='In KES', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL)),
                ('linked_gear', models.ForeignKey(blank=True, help_text='Allows vendors to showcase their available assets in the feed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_posts', to='inventory.inventoryitem')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='community.space')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.post')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
