# Generated by Django 5.2.8 on 2026-03-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='space',
            options={'ordering': ['cluster', 'order', 'name']},
        ),
        migrations.AddField(
            model_name='space',
            name='admin_only_post',
            field=models.BooleanField(default=False, help_text='Only Gigs360 Staff can post here (e.g. Announcements)'),
        ),
        migrations.AddField(
            model_name='space',
            name='cluster',
            field=models.CharField(choices=[('1_general', 'General'), ('2_creatives', 'Photographers & Creators'), ('3_planners', 'Event Planners & Ops'), ('4_vendors', 'Vendors & Gear Marketplace'), ('5_support', 'Help, Inquiries & Complaints')], default='1_general', max_length=20),
        ),
    ]
