from django.db import models
from django.conf import settings
import uuid

# ==========================================
# GIGS360 MASTER ESCROW LEDGER (STAGE 4)
# ==========================================

class MpesaTransaction(models.Model):
    """
    Tracks all C2B (Client to Business) STK Pushes and B2C Payouts via Daraja API.
    """
    TRANSACTION_TYPES = [
        ('C2B_ESCROW', 'Client Deposit to Escrow'),
        ('B2C_PAYOUT', 'Escrow Release to Vendor'),
        ('B2C_REFUND', 'Escrow Refund to Client'),
    ]

    STATUS_CHOICES = [
        ('PENDING', 'Pending User Action (Awaiting PIN)'),
        ('SUCCESS', 'Completed Successfully (Funds Locked)'),
        ('FAILED', 'Transaction Failed/Cancelled'),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    
    # --- RELATIONS ---
    # Links to the specific invoice being paid in the 'events' app
    document = models.ForeignKey('events.Document', on_delete=models.SET_NULL, null=True, blank=True, related_name='mpesa_payments')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True, help_text="User initiating/receiving the transaction")

    # --- TRANSACTION DETAILS ---
    transaction_type = models.CharField(max_length=20, choices=TRANSACTION_TYPES, default='C2B_ESCROW')
    amount = models.DecimalField(max_digits=12, decimal_places=2)
    phone_number = models.CharField(max_length=15, help_text="Format: 2547XXXXXXXX")
    
    # --- DARAJA API TRACKING ---
    # Generated by Safaricom when we trigger the prompt
    merchant_request_id = models.CharField(max_length=100, blank=True, null=True, db_index=True)
    checkout_request_id = models.CharField(max_length=100, blank=True, null=True, unique=True, db_index=True)
    
    # The M-Pesa Receipt (e.g., QWE1234567) generated after successful payment
    receipt_number = models.CharField(max_length=50, blank=True, null=True, unique=True)
    
    # --- STATUS & LOGS ---
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='PENDING')
    result_code = models.CharField(max_length=10, blank=True, null=True, help_text="Safaricom ResultCode (0 is success)")
    result_desc = models.TextField(blank=True, null=True, help_text="Safaricom ResultDesc")
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']
        verbose_name = "M-Pesa Transaction"
        verbose_name_plural = "M-Pesa Transactions"

    def __str__(self):
        return f"{self.receipt_number or 'PENDING'} - KES {self.amount} ({self.status})"