# Generated by Django 5.2.8 on 2025-12-10 12:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='bi-box', help_text='Bootstrap Icon class', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Sony A7S III Body', max_length=200)),
                ('tracking_type', models.CharField(choices=[('UNIQUE', 'Unique (Serialized)'), ('BULK', 'Bulk (Non-Serialized)'), ('CONSUMABLE', 'Sale Item (Gaffer Tape, Batteries)')], default='UNIQUE', max_length=20)),
                ('serial_number', models.CharField(blank=True, help_text='Manufacturer S/N', max_length=100, null=True)),
                ('asset_tag', models.CharField(blank=True, help_text='Internal ID (e.g. CAM-01)', max_length=50, null=True)),
                ('color', models.CharField(blank=True, help_text='e.g. Matte Black', max_length=50, null=True)),
                ('weight', models.CharField(blank=True, help_text='e.g. 2.5kg', max_length=50, null=True)),
                ('condition', models.CharField(choices=[('GOOD', 'Good Condition'), ('FAIR', 'Fair / Scratched'), ('DAMAGED', 'Damaged / Needs Repair'), ('LOST', 'Lost / Stolen')], default='GOOD', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='For Serialized, this is always 1.')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RENTED', 'On Job / Rented'), ('MAINTENANCE', 'In Repair'), ('LOST', 'Lost/Stolen'), ('SOLD', 'Sold/Consumed')], default='AVAILABLE', max_length=20)),
                ('daily_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Rental Price per Day', max_digits=10, null=True)),
                ('replacement_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, help_text='Condition notes, specs...', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='inventory_photos/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category')),
                ('last_scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_items', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
