# Generated by Django 5.2.8 on 2025-12-08 08:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='bi-box', help_text='Bootstrap Icon class', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Sony A7S III Body', max_length=200)),
                ('tracking_type', models.CharField(choices=[('SERIALIZED', 'Unique Item (Camera, Lens)'), ('BULK', 'Bulk/Crate (Chairs, Plates)'), ('CONSUMABLE', 'Sale Item (Gaffer Tape, Batteries)')], default='SERIALIZED', max_length=20)),
                ('serial_number', models.CharField(blank=True, help_text='Manufacturer S/N or Crate ID', max_length=100, null=True)),
                ('quantity', models.IntegerField(default=1, help_text='For Serialized, this is always 1.')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RENTED', 'Rented Out'), ('MAINTENANCE', 'In Repair'), ('LOST', 'Lost/Stolen'), ('SOLD', 'Sold/Consumed')], default='AVAILABLE', max_length=20)),
                ('daily_rate', models.DecimalField(decimal_places=2, help_text='Rental Price per Day', max_digits=10)),
                ('replacement_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, help_text='Condition notes, specs...', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='inventory_photos/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
