# Generated by Django 5.2.8 on 2025-12-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='asset_tag',
            field=models.CharField(blank=True, help_text='Internal ID (e.g. CAM-01)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='color',
            field=models.CharField(blank=True, help_text='e.g. Matte Black', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='condition',
            field=models.CharField(choices=[('GOOD', 'Good Condition'), ('FAIR', 'Fair / Scratched'), ('DAMAGED', 'Damaged / Needs Repair'), ('LOST', 'Lost / Stolen')], default='GOOD', max_length=20),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='weight',
            field=models.CharField(blank=True, help_text='e.g. 2.5kg', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rental Price per Day', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='For Serialized, this is always 1.'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Manufacturer S/N', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='tracking_type',
            field=models.CharField(choices=[('UNIQUE', 'Unique (Serialized)'), ('BULK', 'Bulk (Non-Serialized)'), ('CONSUMABLE', 'Sale Item (Gaffer Tape, Batteries)')], default='UNIQUE', max_length=20),
        ),
    ]
